package tech.codingclub.utility;

import java.io.*;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;

public class FileUtility {

    public static boolean createFile(String fileNameWithPath) {

        File file = new File(fileNameWithPath);

        boolean fileCreated = false;
        try {

            fileCreated = file.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return fileCreated;
    }

    public static ArrayList<String> readandprintfile(String nameOfFile)
    {
        Scanner scanner = null;
        File file = new File(nameOfFile);

        ArrayList <String> strings = new ArrayList<String>();

        try
        {
            scanner = new Scanner(file);
            while(scanner.hasNextLine())
            {
                String data = scanner.nextLine();
                System.out.println(data);
                strings.add(data);
            }
            //scanner.close();
        }

        catch(FileNotFoundException e)
        {
            System.out.println("An error occured");
            e.printStackTrace();
        }

        finally {

            if(scanner != null)
            {
                scanner.close();
            }
        }


        return strings;
    }

    public static boolean writeToFile(String filename, String content)
    {
        try {

            File file = new File(filename);

            FileWriter fw = new FileWriter(filename);
            fw.append(content);
            fw.close();
    } catch (IOException e) {
            return false;
        }
        return true;
    }

        public static boolean appendToFile(String filename, String content)
    {
        try {

            File file = new File(filename);

            FileWriter fw = new FileWriter(filename,true);
            fw.append(content);
            fw.append("\n");
            fw.close();


        } catch (IOException e) {

            return false;
        }
        return true;
    }

    public static ArrayList<String> readFileAsList(String filePath)
    {
        ArrayList<String> data = new ArrayList<String>();
        Scanner scan = null;

        try
        {
            File file = new File(filePath);
            scan = new Scanner(file);

            while(scan.hasNextLine())
            {
                String str = scan.nextLine();
                data.add(str);
            }

        }

        catch (FileNotFoundException e)
        {
            System.out.println("An error occured");
            e.printStackTrace();
        }

        finally {

            if(scan != null)
            {
                scan.close();
            }
        }

        return(data);
    }

    public static void main(String[] args) {

        System.out.println("This is Riya Goyal");
        System.out.println("File Utitlity running at " + new Date().toString());
        //ctrl + shift + c to copy the file path
        String nameOfFile = "E:\\fsd-coding mafia\\techcodingmafia\\data\\practice\\File\\" + "create-file.txt";
        boolean created = createFile(nameOfFile);

        System.out.println("File Created " + created);

        ArrayList<String> arrayOfStrings = readandprintfile(nameOfFile);

        for(String s : arrayOfStrings)
        {
            System.out.println("Line : " + s);
        }

        System.out.println("No. of lines in file : " + arrayOfStrings.size());

        boolean wroteToFile = writeToFile(nameOfFile , "This file is generated by Riya's system automatically.");
        System.out.println(wroteToFile);

        for(int i = 0 ; i<= 100; i++)
        {
            String data = i + "";
            appendToFile(nameOfFile,data);
        }

        System.out.println("Size of the file : " + readandprintfile(nameOfFile).size());
    }
}
